home:
      resource: "routes/home/home.yaml"
      prefix: "/"
      name_prefix: "home_"

#################################################    

auth:
      resource: "routes/home/auth.yaml"
      prefix: "/auth"
      name_prefix: "home_auth_"

#################################################      

cours:
      resource: "routes/home/cours.yaml"
      prefix: "/cours"
      name_prefix: "home_cours_"


#################################################      

merch:
      resource: "routes/home/merch.yaml"
      prefix: "/merch"
      name_prefix: "home_merch_"

#################################################      
donation:
      resource: "routes/home/donation.yaml"
      prefix: "/donation"
      name_prefix: "home_donation_"

#################################################      

quiz:
      resource: "routes/home/quizz.yaml"
      prefix: "/quizz"
      name_prefix: "home_quizz_"

#################################################      

forum:
      resource: "routes/home/forum_chatbot.yaml"
      prefix: "/forum"
      name_prefix: "home_forum_"

#################################################      

avis:
      resource: "routes/home/avis.yaml"
      prefix: "/avis"
      name_prefix: "home_avis_"

###################################################
###################################################
###################################################
###################################################
###################################################
###################################################




teacher_space:
      resource: "routes/teacher/teacher.yaml"
      prefix: "/teacher"
      name_prefix: "teacher_"


      
teacher_cours:
      resource: "routes/teacher/cours.yaml"
      prefix: "/teacher/cours"
      name_prefix: "teacher_cours_"


teacher_quiz:
      resource: "routes/teacher/quiz.yaml"
      prefix: "/teacher/quiz"
      name_prefix: "teacher_quiz_"


###################################################
###################################################
###################################################
###################################################
###################################################
###################################################



admin_space:
      resource: "routes/admin/admin.yaml"
      prefix: "/admin"
      name_prefix: "admin_"

