#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: App\Controller\HomeController::index

cours_filter_index:
  path: /cours
  controller: App\Controller\Cours\FilterController::index

cours_page_index:
  path: /cours/single
  controller: App\Controller\Cours\CoursController::coursPage


cours_lessons_index:
  path: /cours/single/lessons
  controller: App\Controller\Cours\CoursController::coursLessonsPage



cours_quiz_index:
  path: /cours/single/quiz
  controller: App\Controller\Quiz\QuizController::index

cours_quiz_note:
  path: /cours/single/quiz/note
  controller: App\Controller\Quiz\QuizController::note



forum_index:
  path: /forum
  controller: App\Controller\Forum\ForumController::index
