home:
      resource: "routes/home/home.yaml"
      prefix: "/"
      name_prefix: "home_"

#################################################    

auth:
      resource: "routes/home/auth.yaml"
      prefix: "/auth"
      name_prefix: "home_auth_"

#################################################      

cours:
      resource: "routes/home/cours.yaml"
      prefix: "/cours"
      name_prefix: "home_cours_"

#################################################      

quiz:
      resource: "routes/home/quizz.yaml"
      prefix: "/quizz"
      name_prefix: "home_quizz_"

#################################################      

forum:
      resource: "routes/home/forum_chatbot.yaml"
      prefix: "/forum"
      name_prefix: "home_forum_"



###################################################
###################################################
###################################################
###################################################
###################################################
###################################################




teacher_space:
      resource: "routes/teacher/teacher.yaml"
      prefix: "/teacher"
      name_prefix: "teacher_"


      
teacher_cours:
      resource: "routes/teacher/cours.yaml"
      prefix: "/teacher/cours"
      name_prefix: "teacher_cours_"


teacher_quiz:
      resource: "routes/teacher/quiz.yaml"
      prefix: "/teacher/quiz"
      name_prefix: "teacher_quiz_"