#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path: /
  controller: App\Controller\HomeController::index

cours_filter_index:
  path: /cours
  controller: App\Controller\Cours\FilterController::index

cours_page_index:
  path: /cours/single
  controller: App\Controller\Cours\CoursController::coursPage


cours_lessons_index:
  path: /cours/single/lessons
  controller: App\Controller\Cours\CoursController::coursLessonsPage
