load_login_popup:
  path: /load/popup/login
  controller: App\Controller\Auth\AuthController::loadLoginPopup

load_register_popup:
  path: /load/popup/register
  controller: App\Controller\Auth\AuthController::loadRegisterPopup

load_restPws_popup:
  path: /load/popup/reset_pws
  controller: App\Controller\Auth\AuthController::loadResetPwsPopup


register_post:
  path: /register
  controller: App\Controller\Auth\AuthController::register
  methods: [POST]


login_post:
  path: /login
  controller: App\Controller\Auth\AuthController::login
  methods: [POST]

  
logout:
  path: /logout
  controller: App\Controller\Auth\AuthController::logout
 