avis_index:
  path: /avis
  controller: App\Controller\Avis\AvisController::index
ajouter_avis:
  path: /ajouter
  controller: App\Controller\Avis\AvisController::ajouter
  methods: ['POST']
avis_modifier:
  path: /modifier/{id}/{courSlug}
  controller: App\Controller\Avis\AvisController::modifier
avis_supprimer:
  path: /supprimer/{id}
  controller: App\Controller\Avis\AvisController::supprimer
  methods: ['GET']


 