filter_index:
  path: /
  controller: App\Controller\Cours\FilterController::index

page_index:
  path: /{slug}
  controller: App\Controller\Cours\CoursController::coursPage

lessons_index:
  path: /{slug}/lessons
  controller: App\Controller\Cours\CoursController::coursLessonsPage