index:
  path: /
  controller: App\Controller\Forum\ForumController::index

chatbot_index:
  path: /chatbot
  controller: App\Controller\Forum\ForumController::chatBotIndex

delete_publication:
    path: /delete/{idPub}
    controller: App\Controller\Forum\ForumController::deletePublication
    methods: [GET]

delete_comment:
    path: /deleteComment/{idC}
    controller: App\Controller\Forum\ForumController::deleteComment
    methods: [GET]


#################

single_publication:
  path: /single/{idPub}
  controller: App\Controller\Forum\ForumController::single



open_edit_publication:
  path: /edit/{idPub}
  controller: App\Controller\Forum\ForumController::edit
