index:
  path: /
  controller: App\Controller\Forum\ForumController::index

chatbot_index:
  path: /chatbot
  controller: App\Controller\Forum\ForumController::chatBotIndex

delete_publication:
    path: /delete/{idPub}
    controller: App\Controller\Forum\ForumController::deletePublication
    methods: [GET]

delete_comment:
    path: /deleteComment/{idC}
    controller: App\Controller\Forum\ForumController::deleteComment
    methods: [GET]

add_comment:
    path: /add-comment/{idPub}
    controller: App\Controller\Forum\ForumController::addComment
    methods: [POST]

update_comment:
    path: /updateComment
    controller: App\Controller\Forum\ForumController::updateComment
    methods: [POST]

chatbot_action:
    path: /message
    controller: App\Controller\Forum\ForumController::chatBotAction
    methods: [POST]

single_publication:
  path: /single/{idPub}
  controller: App\Controller\Forum\ForumController::single

open_edit_publication:
  path: /edit/{idPub}
  controller: App\Controller\Forum\ForumController::edit

update_publication:
  path: /update-publication/{idPub}
  controller: App\Controller\Forum\ForumController::updatePublication
  methods: [POST]



