index:
  path: /single
  controller: App\Controller\Quiz\QuizController::index

note:
  path: /single/note
  controller: App\Controller\Quiz\QuizController::note

quiz_question:
    path: /single/{coursId}/question/{questionIndex}
    controller: App\Controller\Quiz\QuizController::index
    defaults:
        questionIndex: 0 # Default value if not provided
    requirements:
        coursId: '\d+' # coursId must be a number
        questionIndex: '\d+' # questionIndex must be a number