index:
  path: /
  controller: App\Controller\Teacher\TeacherCoursController::index


add:
  path: /ajouter
  controller: App\Controller\Teacher\TeacherCoursController::add


add_lesson:
  path: /add_lesson
  controller: App\Controller\Teacher\TeacherCoursController::add_lesson

