index:
  path: /
  controller: App\Controller\Teacher\TeacherCoursController::index


add:
  path: /ajouter
  controller: App\Controller\Teacher\TeacherCoursController::add


add_lesson:
  path: /add_lesson
  controller: App\Controller\Teacher\TeacherCoursController::add_lesson



create:
  path: /create 
  controller: App\Controller\Teacher\TeacherCoursController::create
  methods: [POST]


  
delete:
  path: /delete/{id} 
  controller: App\Controller\Teacher\TeacherCoursController::delete 

  ##################################

edit:
  path: /edit/{id}
  controller: App\Controller\Teacher\TeacherCoursController::edit


update:
  path: /update 
  controller: App\Controller\Teacher\TeacherCoursController::update
  methods: [POST]
