index:
  path: /
  controller: App\Controller\Teacher\TeacherQuizController::index


preview_popup:
  path: /preview_popup/{quiz_id}
  controller: App\Controller\Teacher\TeacherQuizController::preview




add:
  path: /ajouter/{cours_id}
  controller: App\Controller\Teacher\TeacherQuizController::add


add_question:
  path: /add_question
  controller: App\Controller\Teacher\TeacherQuizController::add_question



create:
  path: /create 
  controller: App\Controller\Teacher\TeacherQuizController::create
  methods: [POST]