index:
  path: /
  controller: App\Controller\Teacher\TeacherController::index




students:
  path: /students
  controller: App\Controller\Teacher\TeacherController::students_page
  methods: [GET, POST]


students_datatable:
  path: /students_datatble
  controller: App\Controller\Teacher\TeacherController::datatableData
  methods: [GET, POST]

 