dashboard:
  path: /
  controller: App\Controller\Admin\AdminController::index




#################################################################
#################################################################
#################################################################
#################################################################
classification_category_page:
  path: /classification/category
  controller: App\Controller\Admin\ClassificationController::category

classification_category_create:
  path: /classification/category/create
  controller: App\Controller\Admin\ClassificationController::category_create


#########
classification_subcategory_page:
  path: /classification/subcategory
  controller: App\Controller\Admin\ClassificationController::subcategory

classification_subcategory_create:
  path: /classification/subcategory/create
  controller: App\Controller\Admin\ClassificationController::subcategory_create

  ####################

category_list:
    path: /category
    controller: App\Controller\Categorie\CategorieController::category

subcategory_list:
    path: /subcategory
    controller: App\Controller\Categorie\CategorieController::subcategory

category_create:
  path: /category/create
  controller: App\Controller\Categorie\CategorieController::category_create

subcategory_create:
  path: /subcategory/create
  controller: App\Controller\Categorie\CategorieController::subcategory_create




#################################################################
#################################################################
#################################################################
#################################################################





users:
  path: /users 
  controller: App\Controller\Admin\AdminController::users


get_users_list:
  path: /users/datatable 
  controller: App\Controller\Admin\AdminController::users_list


delete_user:
  path: /users/delete/{id} 
  controller: App\Controller\Admin\AdminController::delete_user




  

#################################################################
#################################################################
#################################################################
#################################################################
#################################################################
#################################################################
#################################################################
#################################################################

reclamations:
  path: /reclamations 
  controller: App\Controller\Admin\ReclamationController::index
  
single_reclamation:
  path: /reclamations/{id} 
  controller: App\Controller\Admin\ReclamationController::single
  methods: ['GET']

modifier_statut_reclamation:
  path: /reclamation/{id}/modifier_statut
  controller: App\Controller\Admin\ReclamationController::modifierStatut
  methods: ['POST']

supprimer_reclamation:
  path: /reclamations/supprimer/{id} 
  controller: App\Controller\Admin\ReclamationController::delete_Rec
envoyer_mail_Rec:
  path: /reclamations/envoyer_mail/{userId}/{id} 
  controller: App\Controller\Admin\ReclamationController::sendEmailToUserAction



#################################################################
#################################################################
#################################################################
#################################################################

forum_index:
  path: /forum 
  controller: App\Controller\Admin\ForumController::index
  
single_publication:
  path: /forum/{id} 
  controller: App\Controller\Admin\ForumController::single
  methods: ['GET']

supprimer_publication:
  path: /forum/supprimer/{id} 
  controller: App\Controller\Admin\ForumController::deletePublication


#################################################################
#################################################################
#################################################################
#################################################################

quiz_index:
  path: /quiz 
  controller: App\Controller\Admin\QuizController::index

quiz_view:
  path: /quiz/{id} 
  controller: App\Controller\Admin\QuizController::view
  methods: ['GET']

quiz_delete:
  path: /quiz/delete/{id} 
  controller: App\Controller\Admin\QuizController::delete

